// Made by Bruce Cosgrove

enum Opcodes {
	NOP = 0x00, LD_BC_NN, LD_pBC_A, INC_BC, INC_B, DEC_B, LD_B_N, RLCA, EX_AF_AFp, ADD_HL_BC, LD_A_pBC, DEC_BC, INC_C, DEC_C, LD_C_N, RRCA,
	DJNZ_N, LD_DE_NN, LD_pDE_A, INC_DE, INC_D, DEC_D, LD_D_N, RLA, JR_N, ADD_HL_DE, LD_A_pDE, DEC_DE, INC_E, DEC_E, LD_E_N, RRA,
	JR_NZ_N, LD_HL_NN, LD_pNN_HL, INC_HL, INC_H, DEC_H, LD_H_N, DAA, JR_Z_N, ADD_HL_HL, LD_HL_pNN, DEC_HL, INC_L, DEC_L, LD_L_N, CPL,
	JR_NC_N, LD_SP_NN, LD_pNN_A, INC_SP, INC_pHL, DEC_pHL, LD_pHL_*, SCF, JR_C_N, ADD_HL_SP, LD_A_pNN, DEC_SP, INC_A, DEC_A, LD_A_N, CCF,
	LD_B_B, LD_B_C, LD_B_D, LD_B_E, LD_B_H, LD_B_L, LD_B_pHL, LD_B_A, LD_C_B, LD_C_C, LD_C_D, LD_C_E, LD_C_H, LD_C_L, LD_C_pHL, LD_C_A,
	LD_D_B, LD_D_C, LD_D_D, LD_D_E, LD_D_H, LD_D_L, LD_D_pHL, LD_D_A, LD_E_B, LD_E_C, LD_E_D, LD_E_E, LD_E_H, LD_E_L, LD_E_pHL, LD_E_A,
	LD_H_B, LD_H_C, LD_H_D, LD_H_E, LD_H_H, LD_H_L, LD_H_pHL, LD_H_A, LD_L_B, LD_L_C, LD_L_D, LD_L_E, LD_L_H, LD_L_L, LD_L_pHL, LD_L_A,
	LD_pHL_B, LD_pHL_C, LD_pHL_D, LD_pHL_E, LD_pHL_H, LD_pHL_L, HALT, LD_pHL_A, LD_A_B, LD_A_C, LD_A_D, LD_A_E, LD_A_H, LD_A_L, LD_A_pHL, LD_A_A,
	ADD_A_B, ADD_A_C, ADD_A_D, ADD_A_E, ADD_A_H, ADD_A_L, ADD_A_pHL, ADD_A_A, ADC_A_B, ADC_A_C, ADC_A_D, ADC_A_E, ADC_A_H, ADC_A_L, ADC_A_pHL, ADC_A_A,
	SUB_B, SUB_C, SUB_D, SUB_E, SUB_H, SUB_L, SUB_pHL, SUB_A, SBC_A_B, SBC_A_C, SBC_A_D, SBC_A_E, SBC_A_H, SBC_A_L, SBC_A_pHL, SBC_A_A,
	AND_B, AND_C, AND_D, AND_E, AND_H, AND_L, AND_pHL, AND_A, XOR_B, XOR_C, XOR_D, XOR_E, XOR_H, XOR_L, XOR_pHL, XOR_A,
	OR_B, OR_C, OR_D, OR_E, OR_H, OR_L, OR_pHL, OR_A, CP_B, CP_C, CP_D, CP_E, CP_H, CP_L, CP_pHL, CP_A,
	RET_NZ, POP_BC, JP_NZ_NN, JP_NN, CALL_NZ_NN, PUSH_BC, ADD_A_N, RST_00H, RET_Z, RET, JP_Z_NN, bits_section, CALL_Z_NN, CALL_NN, ADC_A_N, RST_08H,
	RET_NC, POP_DE, JP_NC_NN, OUT_N_A, CALL_NC_NN, PUSH_DE, SUB_N, RST_10H, RET_C, EXX, JP_C_NN, IN_A_N, CALL_C_NN, ix_section, SBC_A_N, RST_18H,
	RET_PO, POP_HL, JP_PO_NN, EX_pSP_HL, CALL_PO_NN, PUSH_HL, AND_N, RST_20H, RET_PE, JP_pHL, JP_PE_NN, EX_DE_HL, CALL_PE_NN, extended_section, XOR_N, RST_28H,
	RET_P, POP_AF, JP_P_NN, DI, CALL_P_NN, PUSH_AF, OR_N, RST_30H, RET_M, LD_SP_HL, JP_M_NN, EI, CALL_M_NN, iy_section, CP_N, RST_38H
};

enum OpcodesExtended {
	IN_B_pC = 0x40, OUT_pC_B, SBC_HL_BC, LD_pNN_BC, NEG, RETN, IM_0, LD_I_A, IN_C_pC, OUT_pC_C, ADC_HL_BC, LD_BC_pNN, NEG_ILLEGAL, RETI, IM_0_1_ILLEGAL, LD_R_A,
	IN_D_pC, OUT_pC_D, SBC_HL_DE, LD_pNN_DE, NEG_ILLEGAL, RETN, IM_1, LD_A_I, IN_E_pC, OUT_pC_E, ADC_HL_DE, LD_DE_NN, NEG_ILLEGAL, RETN, IM_2, LD_A_R,
	IN_H_pC, OUT_pC_H, SBC_HL_HL, LD_pNN_HL_ILLEGAL, NEG_ILLEGAL, RETN, IM_0, RRD, IN_L_pC, OUT_pC_L, ADC_HL_HL, LD_HL_pNN_ILLEGAL, NEG_ILLEGAL, RETN, IM_0_1_ILLEGAL, RLD,
	IN_pC_ILLEGAL, OUT_pC_0_ILLEGAL, SBC_HL_SP, LD_pNN_SP, NEG_ILLEGAL, RETN, IM_1, /*EMPTY*/  IN_A_pC = 0x78, OUT_pC_A, ADC_HL_SP, LD_SP_pNN, NEG_ILLEGAL, RETN, IM_2, /*EMPTY*/
	LDI = 0xa0, CPI, INI, OUTI, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LDD, CPD, IND, OUTD, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	LDIR = 0xb0, CPIR, INIR, OTDR, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LDDR, CPDR, INDR, OTDR, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
};

enum OpcodesBits {
	RLC_B = 0x00, RLC_C, RLC_D, RLC_E, RLC_H, RLC_L, RLC_pHL, RLC_A, RRC_B, RRC_C, RRC_D, RRC_E, RRC_H, RRC_L, RRC_pHL, RRC_A,
	RL_B, RL_C, RL_D, RL_E, RL_H, RL_L, RL_pHL, RL_A, RR_B, RR_C, RR_D, RR_E, RR_H, RR_L, RR_pHL, RR_A,
	SLA_B, SLA_C, SLA_D, SLA_E, SLA_H, SLA_L, SLA_pHL, SLA_A, SRA_B, SRA_C, SRA_D, SRA_E, SRA_H, SRA_L, SRA_pHL, SRA_A,
	sll_B_ILLEGAL, sll_C_ILLEGAL, sll_D_ILLEGAL, sll_E_ILLEGAL, sll_H_ILLEGAL, sll_L_ILLEGAL, sll_pHL_ILLEGAL, sll_A_ILLEGAL, srl_B, srl_C, srl_D, srl_E, srl_H, srl_L, srl_pHL, srl_A,
	BIT 0_B, BIT 0_C, BIT 0_D, BIT 0_E, BIT 0_H, BIT 0_L, BIT 0_pHL, BIT 0_A, BIT 1_B, BIT 1_C, BIT 1_D, BIT 1_E, BIT 1_H, BIT 1_L, BIT 1_pHL, BIT 1_A,
	BIT 2_B, BIT 2_C, BIT 2_D, BIT 2_E, BIT 2_H, BIT 2_L, BIT 2_pHL, BIT 2_A, BIT 3_B, BIT 3_C, BIT 3_D, BIT 3_E, BIT 3_H, BIT 3_L, BIT 3_pHL, BIT 3_A,
	BIT 4_B, BIT 4_C, BIT 4_D, BIT 4_E, BIT 4_H, BIT 4_L, BIT 4_pHL, BIT 4_A, BIT 5_B, BIT 5_C, BIT 5_D, BIT 5_E, BIT 5_H, BIT 5_L, BIT 5_pHL, BIT 5_A,
	BIT 6_B, BIT 6_C, BIT 6_D, BIT 6_E, BIT 6_H, BIT 6_L, BIT 6_pHL, BIT 6_A, BIT 7_B, BIT 7_C, BIT 7_D, BIT 7_E, BIT 7_H, BIT 7_L, BIT 7_pHL, BIT 7_A,
	RES 0_B, RES 0_C, RES 0_D, RES 0_E, RES 0_H, RES 0_L, RES 0_pHL, RES 0_A, RES 1_B, RES 1_C, RES 1_D, RES 1_E, RES 1_H, RES 1_L, RES 1_pHL, RES 1_A,
	RES 2_B, RES 2_C, RES 2_D, RES 2_E, RES 2_H, RES 2_L, RES 2_pHL, RES 2_A, RES 3_B, RES 3_C, RES 3_D, RES 3_E, RES 3_H, RES 3_L, RES 3_pHL, RES 3_A,
	RES 4_B, RES 4_C, RES 4_D, RES 4_E, RES 4_H, RES 4_L, RES 4_pHL, RES 4_A, RES 5_B, RES 5_C, RES 5_D, RES 5_E, RES 5_H, RES 5_L, RES 5_pHL, RES 5_A,
	RES 6_B, RES 6_C, RES 6_D, RES 6_E, RES 6_H, RES 6_L, RES 6_pHL, RES 6_A, RES 7_B, RES 7_C, RES 7_D, RES 7_E, RES 7_H, RES 7_L, RES 7_pHL, RES 7_A,
	SET 0_B, SET 0_C, SET 0_D, SET 0_E, SET 0_H, SET 0_L, SET 0_pHL, SET 0_A, SET 1_B, SET 1_C, SET 1_D, SET 1_E, SET 1_H, SET 1_L, SET 1_pHL, SET 1_A,
	SET 2_B, SET 2_C, SET 2_D, SET 2_E, SET 2_H, SET 2_L, SET 2_pHL, SET 2_A, SET 3_B, SET 3_C, SET 3_D, SET 3_E, SET 3_H, SET 3_L, SET 3_pHL, SET 3_A,
	SET 4_B, SET 4_C, SET 4_D, SET 4_E, SET 4_H, SET 4_L, SET 4_pHL, SET 4_A, SET 5_B, SET 5_C, SET 5_D, SET 5_E, SET 5_H, SET 5_L, SET 5_pHL, SET 5_A,
	SET 6_B, SET 6_C, SET 6_D, SET 6_E, SET 6_H, SET 6_L, SET 6_pHL, SET 6_A, SET 7_B, SET 7_C, SET 7_D, SET 7_E, SET 7_H, SET 7_L, SET 7_pHL, SET 7_A
};

enum OpcodesIX {
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ ADD_IX_BC = 0x09, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ ADD_IX_DE = 0x19, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ LD_IX_NN = 0x21, LD_pNN_IX, INC_IX, INC_IXH_ILLEGAL, DEC_IXH_ILLEGAL, LD_IXH_N_ILLEGAL, /*EMPTY*/ /*EMPTY*/ ADD_IX_IX = 0x29, LD_IX_pNN, DEC_IX, INC_IXL_ILLEGAL, DEC_IXL_ILLEGAL, LD_IXL_N_ILLEGAL, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ INC_pIXpN = 0x34, DEC_pIXpN, LD_pIXpN_N, /*EMPTY*/ /*EMPTY*/ ADD_IX_SP = 0x39, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_B_IXH_ILLEGAL = 0x44, LD_B_IXL_ILLEGAL, LD_B_pIXpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_C_IXH_ILLEGAL = 0x4c, LD_C_IXL_ILLEGAL, LD_C_pIXpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_D_IXH_ILLEGAL = 0x54, LD_D_IXL_ILLEGAL, LD_D_pIXpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_E_IXH_ILLEGAL = 0x5c, LD_E_IXL_ILLEGAL, LD_E_pIXpN, /*EMPTY*/
	LD_IXH_B_ILLEGAL = 0x60, LD_IXH_C_ILLEGAL, LD_IXH_D_ILLEGAL, LD_IXH_E_ILLEGAL, LD_IXH_IXH_ILLEGAL, LD_IXH_IXL_ILLEGAL, LD_H_pIXpN, LD_IXH_A_ILLEGAL, LD_IXL_B_ILLEGAL, LD_IXL_C_ILLEGAL, LD_IXL_D_ILLEGAL, LD_IXL_E_ILLEGAL, LD_IXL_IXH_ILLEGAL, LD_IXL_IXL_ILLEGAL, LH_L_pIXpN, LD_IXL_A_ILLEGAL,
	LD_pIXpN_B, LD_pIXpN_C, LD_pIXpN_D, LD_pIXpN_E, LD_pIXpN_H, LD_pIXpN_L, /*EMPTY*/ LD_pIXpN_A = 0x77, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_A_IXH_ILLEGAL = 0x7c, LD_A_IXL_ILLEGAL, LH_A_pIXpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ ADD_A_IXH = 0x84, ADD_A_IXL, ADD_A_pIXpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ ADC_A_IXH = 0x8c, ADC_A_IXL, ADC_A_pIXpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ SUB_A_IXH = 0x94, SUB_A_IXL, SUB_A_pIXpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ SBC_A_IXH = 0x9c, SBC_A_IXL, SBC_A_pIXpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ AND_A_IXH = 0xa4, AND_A_IXL, AND_A_pIXpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ XOR_A_IXH = 0xac, XOR_A_IXL, XOR_A_pIXpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ OR_A_IXH = 0xb4, OR_A_IXL, OR_A_pIXpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ CP_A_IXH = 0xbc, CP_A_IXL, CP_A_pIXpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ IX_bits = 0xcb, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ POP_IX = 0xe1, /*EMPTY*/ EX_pSP_IX = 0xe3, /*EMPTY*/ PUSH_IX = 0xe5, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ JP_pIX = 0xe9, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_SP_IX = 0xf9, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
};

enum OpcodesIXBits {
	RLC_pIXpN_B_ILLEGAL = 0x00, RLC_pIXpN_C_ILLEGAL, RLC_pIXpN_D_ILLEGAL, RLC_pIXpN_E_ILLEGAL, RLC_pIXpN_H_ILLEGAL, RLC_pIXpN_L_ILLEGAL, RLC_pIXpN, RLC_pIXpN_A_ILLEGAL, RRC_pIXpN__ILLEGALB, RRC_pIXpN_C_ILLEGAL, RRC_pIXpN_D_ILLEGAL, RRC_pIXpN_E_ILLEGAL, RRC_pIXpN_H_ILLEGAL, RRC_pIXpN_L_ILLEGAL, RRC_pIXpN, RRC_pIXpN_A_ILLEGAL,
	RL_pIXpN_B_ILLEGAL, RL_pIXpN_C_ILLEGAL, RL_pIXpN_D_ILLEGAL, RL_pIXpN_E_ILLEGAL, RL_pIXpN_H_ILLEGAL, RL_pIXpN_L_ILLEGAL, RL_pIXpN, RL_pIXpN_A_ILLEGAL, RR_pIXpN__ILLEGALB, RR_pIXpN_C_ILLEGAL, RR_pIXpN_D_ILLEGAL, RR_pIXpN_E_ILLEGAL, RR_pIXpN_H_ILLEGAL, RR_pIXpN_L_ILLEGAL, RR_pIXpN, RR_pIXpN_A_ILLEGAL,
	SLA_pIXpN_B_ILLEGAL, SLA_pIXpN_C_ILLEGAL, SLA_pIXpN_D_ILLEGAL, SLA_pIXpN_E_ILLEGAL, SLA_pIXpN_H_ILLEGAL, SLA_pIXpN_L_ILLEGAL, SLA_pIXpN, SLA_pIXpN_A_ILLEGAL, SRA_pIXpN__ILLEGALB, SRA_pIXpN_C_ILLEGAL, SRA_pIXpN_D_ILLEGAL, SRA_pIXpN_E_ILLEGAL, SRA_pIXpN_H_ILLEGAL, SRA_pIXpN_L_ILLEGAL, SRA_pIXpN, SRA_pIXpN_A_ILLEGAL,
	SLL_pIXpN_B_ILLEGAL, SLL_pIXpN_C_ILLEGAL, SLL_pIXpN_D_ILLEGAL, SLL_pIXpN_E_ILLEGAL, SLL_pIXpN_H_ILLEGAL, SLL_pIXpN_L_ILLEGAL, SLL_pIXpN_ILLEGAL, SLL_pIXpN_A_ILLEGAL, SRL_pIXpN__ILLEGALB, SRL_pIXpN_C_ILLEGAL, SRL_pIXpN_D_ILLEGAL, SRL_pIXpN_E_ILLEGAL, SRL_pIXpN_H_ILLEGAL, SRL_pIXpN_L_ILLEGAL, SRL_pIXpN, SRL_pIXpN_A_ILLEGAL,
	BIT_0_pIXpN_ILLEGAL_0, BIT_0_pIXpN_ILLEGAL_1, BIT_0_pIXpN_ILLEGAL_2, BIT_0_pIXpN_ILLEGAL_3, BIT_0_pIXpN_ILLEGAL_4, BIT_0_pIXpN_ILLEGAL_5, BIT_0_pIXpN, BIT_0_pIXpN_ILLEGAL_7, BIT_1_pIXpN_ILLEGAL_0, BIT_1_pIXpN_ILLEGAL_1, BIT_1_pIXpN_ILLEGAL_2, BIT_1_pIXpN_ILLEGAL_3, BIT_1_pIXpN_ILLEGAL_4, BIT_1_pIXpN_ILLEGAL_5, BIT_1_pIXpN, BIT_1_pIXpN_A_ILLEGAL_7,
	BIT_2_pIXpN_ILLEGAL_0, BIT_2_pIXpN_ILLEGAL_1, BIT_2_pIXpN_ILLEGAL_2, BIT_2_pIXpN_ILLEGAL_3, BIT_2_pIXpN_ILLEGAL_4, BIT_2_pIXpN_ILLEGAL_5, BIT_2_pIXpN, BIT_2_pIXpN_ILLEGAL_7, BIT_3_pIXpN_ILLEGAL_0, BIT_3_pIXpN_ILLEGAL_1, BIT_3_pIXpN_ILLEGAL_2, BIT_3_pIXpN_ILLEGAL_3, BIT_3_pIXpN_ILLEGAL_4, BIT_3_pIXpN_ILLEGAL_5, BIT_3_pIXpN, BIT_3_pIXpN_A_ILLEGAL_7,
	BIT_4_pIXpN_ILLEGAL_0, BIT_4_pIXpN_ILLEGAL_1, BIT_4_pIXpN_ILLEGAL_2, BIT_4_pIXpN_ILLEGAL_3, BIT_4_pIXpN_ILLEGAL_4, BIT_4_pIXpN_ILLEGAL_5, BIT_4_pIXpN, BIT_4_pIXpN_ILLEGAL_7, BIT_5_pIXpN_ILLEGAL_0, BIT_5_pIXpN_ILLEGAL_1, BIT_5_pIXpN_ILLEGAL_2, BIT_5_pIXpN_ILLEGAL_3, BIT_5_pIXpN_ILLEGAL_4, BIT_5_pIXpN_ILLEGAL_5, BIT_5_pIXpN, BIT_5_pIXpN_A_ILLEGAL_7,
	BIT_6_pIXpN_ILLEGAL_0, BIT_6_pIXpN_ILLEGAL_1, BIT_6_pIXpN_ILLEGAL_2, BIT_6_pIXpN_ILLEGAL_3, BIT_6_pIXpN_ILLEGAL_4, BIT_6_pIXpN_ILLEGAL_5, BIT_6_pIXpN, BIT_6_pIXpN_ILLEGAL_7, BIT_7_pIXpN_ILLEGAL_0, BIT_7_pIXpN_ILLEGAL_1, BIT_7_pIXpN_ILLEGAL_2, BIT_7_pIXpN_ILLEGAL_3, BIT_7_pIXpN_ILLEGAL_4, BIT_7_pIXpN_ILLEGAL_5, BIT_7_pIXpN, BIT_7_pIXpN_A_ILLEGAL_7,
	RES_0_pIXpN_ILLEGAL_0, RES_0_pIXpN_ILLEGAL_1, RES_0_pIXpN_ILLEGAL_2, RES_0_pIXpN_ILLEGAL_3, RES_0_pIXpN_ILLEGAL_4, RES_0_pIXpN_ILLEGAL_5, RES_0_pIXpN, RES_0_pIXpN_ILLEGAL_7, RES_1_pIXpN_ILLEGAL_0, RES_1_pIXpN_ILLEGAL_1, RES_1_pIXpN_ILLEGAL_2, RES_1_pIXpN_ILLEGAL_3, RES_1_pIXpN_ILLEGAL_4, RES_1_pIXpN_ILLEGAL_5, RES_1_pIXpN, RES_1_pIXpN_A_ILLEGAL_7,
	RES_2_pIXpN_ILLEGAL_0, RES_2_pIXpN_ILLEGAL_1, RES_2_pIXpN_ILLEGAL_2, RES_2_pIXpN_ILLEGAL_3, RES_2_pIXpN_ILLEGAL_4, RES_2_pIXpN_ILLEGAL_5, RES_2_pIXpN, RES_2_pIXpN_ILLEGAL_7, RES_3_pIXpN_ILLEGAL_0, RES_3_pIXpN_ILLEGAL_1, RES_3_pIXpN_ILLEGAL_2, RES_3_pIXpN_ILLEGAL_3, RES_3_pIXpN_ILLEGAL_4, RES_3_pIXpN_ILLEGAL_5, RES_3_pIXpN, RES_3_pIXpN_A_ILLEGAL_7,
	RES_4_pIXpN_ILLEGAL_0, RES_4_pIXpN_ILLEGAL_1, RES_4_pIXpN_ILLEGAL_2, RES_4_pIXpN_ILLEGAL_3, RES_4_pIXpN_ILLEGAL_4, RES_4_pIXpN_ILLEGAL_5, RES_4_pIXpN, RES_4_pIXpN_ILLEGAL_7, RES_5_pIXpN_ILLEGAL_0, RES_5_pIXpN_ILLEGAL_1, RES_5_pIXpN_ILLEGAL_2, RES_5_pIXpN_ILLEGAL_3, RES_5_pIXpN_ILLEGAL_4, RES_5_pIXpN_ILLEGAL_5, RES_5_pIXpN, RES_5_pIXpN_A_ILLEGAL_7,
	RES_6_pIXpN_ILLEGAL_0, RES_6_pIXpN_ILLEGAL_1, RES_6_pIXpN_ILLEGAL_2, RES_6_pIXpN_ILLEGAL_3, RES_6_pIXpN_ILLEGAL_4, RES_6_pIXpN_ILLEGAL_5, RES_6_pIXpN, RES_6_pIXpN_ILLEGAL_7, RES_7_pIXpN_ILLEGAL_0, RES_7_pIXpN_ILLEGAL_1, RES_7_pIXpN_ILLEGAL_2, RES_7_pIXpN_ILLEGAL_3, RES_7_pIXpN_ILLEGAL_4, RES_7_pIXpN_ILLEGAL_5, RES_7_pIXpN, RES_7_pIXpN_A_ILLEGAL_7,
	SET_0_pIXpN_ILLEGAL_0, SET_0_pIXpN_ILLEGAL_1, SET_0_pIXpN_ILLEGAL_2, SET_0_pIXpN_ILLEGAL_3, SET_0_pIXpN_ILLEGAL_4, SET_0_pIXpN_ILLEGAL_5, SET_0_pIXpN, SET_0_pIXpN_ILLEGAL_7, SET_1_pIXpN_ILLEGAL_0, SET_1_pIXpN_ILLEGAL_1, SET_1_pIXpN_ILLEGAL_2, SET_1_pIXpN_ILLEGAL_3, SET_1_pIXpN_ILLEGAL_4, SET_1_pIXpN_ILLEGAL_5, SET_1_pIXpN, SET_1_pIXpN_A_ILLEGAL_7,
	SET_2_pIXpN_ILLEGAL_0, SET_2_pIXpN_ILLEGAL_1, SET_2_pIXpN_ILLEGAL_2, SET_2_pIXpN_ILLEGAL_3, SET_2_pIXpN_ILLEGAL_4, SET_2_pIXpN_ILLEGAL_5, SET_2_pIXpN, SET_2_pIXpN_ILLEGAL_7, SET_3_pIXpN_ILLEGAL_0, SET_3_pIXpN_ILLEGAL_1, SET_3_pIXpN_ILLEGAL_2, SET_3_pIXpN_ILLEGAL_3, SET_3_pIXpN_ILLEGAL_4, SET_3_pIXpN_ILLEGAL_5, SET_3_pIXpN, SET_3_pIXpN_A_ILLEGAL_7,
	SET_4_pIXpN_ILLEGAL_0, SET_4_pIXpN_ILLEGAL_1, SET_4_pIXpN_ILLEGAL_2, SET_4_pIXpN_ILLEGAL_3, SET_4_pIXpN_ILLEGAL_4, SET_4_pIXpN_ILLEGAL_5, SET_4_pIXpN, SET_4_pIXpN_ILLEGAL_7, SET_5_pIXpN_ILLEGAL_0, SET_5_pIXpN_ILLEGAL_1, SET_5_pIXpN_ILLEGAL_2, SET_5_pIXpN_ILLEGAL_3, SET_5_pIXpN_ILLEGAL_4, SET_5_pIXpN_ILLEGAL_5, SET_5_pIXpN, SET_5_pIXpN_A_ILLEGAL_7,
	SET_6_pIXpN_ILLEGAL_0, SET_6_pIXpN_ILLEGAL_1, SET_6_pIXpN_ILLEGAL_2, SET_6_pIXpN_ILLEGAL_3, SET_6_pIXpN_ILLEGAL_4, SET_6_pIXpN_ILLEGAL_5, SET_6_pIXpN, SET_6_pIXpN_ILLEGAL_7, SET_7_pIXpN_ILLEGAL_0, SET_7_pIXpN_ILLEGAL_1, SET_7_pIXpN_ILLEGAL_2, SET_7_pIXpN_ILLEGAL_3, SET_7_pIXpN_ILLEGAL_4, SET_7_pIXpN_ILLEGAL_5, SET_7_pIXpN, SET_7_pIXpN_A_ILLEGAL_7
};

enum OpcodesIY {
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ ADD_IY_BC = 0x09, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ ADD_IY_DE = 0x19, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ LD_IY_NN = 0x21, LD_pNN_IY, INC_IY, INC_IYH_ILLEGAL, DEC_IYH_ILLEGAL, LD_IYH_N_ILLEGAL, /*EMPTY*/ /*EMPTY*/ ADD_IY_IY = 0x29, LD_IY_pNN, DEC_IY, INC_IYL_ILLEGAL, DEC_IYL_ILLEGAL, LD_IYL_N_ILLEGAL, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ INC_pIYpN = 0x34, DEC_pIYpN, LD_pIYpN_N, /*EMPTY*/ /*EMPTY*/ ADD_IY_SP = 0x39, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_B_IYH_ILLEGAL = 0x44, LD_B_IYL_ILLEGAL, LD_B_pIYpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_C_IYH_ILLEGAL = 0x4c, LD_C_IYL_ILLEGAL, LD_C_pIYpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_D_IYH_ILLEGAL = 0x54, LD_D_IYL_ILLEGAL, LD_D_pIYpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_E_IYH_ILLEGAL = 0x5c, LD_E_IYL_ILLEGAL, LD_E_pIYpN, /*EMPTY*/
	LD_IYH_B_ILLEGAL = 0x60, LD_IYH_C_ILLEGAL, LD_IYH_D_ILLEGAL, LD_IYH_E_ILLEGAL, LD_IYH_IYH_ILLEGAL, LD_IYH_IYL_ILLEGAL, LD_H_pIYpN, LD_IYH_A_ILLEGAL, LD_IYL_B_ILLEGAL, LD_IYL_C_ILLEGAL, LD_IYL_D_ILLEGAL, LD_IYL_E_ILLEGAL, LD_IYL_IYH_ILLEGAL, LD_IYL_IYL_ILLEGAL, LH_L_pIYpN, LD_IYL_A_ILLEGAL,
	LD_pIYpN_B, LD_pIYpN_C, LD_pIYpN_D, LD_pIYpN_E, LD_pIYpN_H, LD_pIYpN_L, /*EMPTY*/ LD_pIYpN_A = 0x77, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_A_IYH_ILLEGAL = 0x7c, LD_A_IYL_ILLEGAL, LH_A_pIYpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ ADD_A_IYH = 0x84, ADD_A_IYL, ADD_A_pIYpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ ADC_A_IYH = 0x8c, ADC_A_IYL, ADC_A_pIYpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ SUB_A_IYH = 0x94, SUB_A_IYL, SUB_A_pIYpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ SBC_A_IYH = 0x9c, SBC_A_IYL, SBC_A_pIYpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ AND_A_IYH = 0xa4, AND_A_IYL, AND_A_pIYpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ XOR_A_IYH = 0xac, XOR_A_IYL, XOR_A_pIYpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ OR_A_IYH = 0xb4, OR_A_IYL, OR_A_pIYpN, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ CP_A_IYH = 0xbc, CP_A_IYL, CP_A_pIYpN, /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ IY_bits = 0xcb, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ POP_IY = 0xe1, /*EMPTY*/ EX_pSP_IY = 0xe3, /*EMPTY*/ PUSH_IY = 0xe5, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ JP_pIY = 0xe9, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
	/*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ LD_SP_IY = 0xf9, /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/ /*EMPTY*/
};

enum OpcodesIYBits {
	RLC_pIYpN_B_ILLEGAL = 0x00, RLC_pIYpN_C_ILLEGAL, RLC_pIYpN_D_ILLEGAL, RLC_pIYpN_E_ILLEGAL, RLC_pIYpN_H_ILLEGAL, RLC_pIYpN_L_ILLEGAL, RLC_pIYpN, RLC_pIYpN_A_ILLEGAL, RRC_pIYpN__ILLEGALB, RRC_pIYpN_C_ILLEGAL, RRC_pIYpN_D_ILLEGAL, RRC_pIYpN_E_ILLEGAL, RRC_pIYpN_H_ILLEGAL, RRC_pIYpN_L_ILLEGAL, RRC_pIYpN, RRC_pIYpN_A_ILLEGAL,
	RL_pIYpN_B_ILLEGAL, RL_pIYpN_C_ILLEGAL, RL_pIYpN_D_ILLEGAL, RL_pIYpN_E_ILLEGAL, RL_pIYpN_H_ILLEGAL, RL_pIYpN_L_ILLEGAL, RL_pIYpN, RL_pIYpN_A_ILLEGAL, RR_pIYpN__ILLEGALB, RR_pIYpN_C_ILLEGAL, RR_pIYpN_D_ILLEGAL, RR_pIYpN_E_ILLEGAL, RR_pIYpN_H_ILLEGAL, RR_pIYpN_L_ILLEGAL, RR_pIYpN, RR_pIYpN_A_ILLEGAL,
	SLA_pIYpN_B_ILLEGAL, SLA_pIYpN_C_ILLEGAL, SLA_pIYpN_D_ILLEGAL, SLA_pIYpN_E_ILLEGAL, SLA_pIYpN_H_ILLEGAL, SLA_pIYpN_L_ILLEGAL, SLA_pIYpN, SLA_pIYpN_A_ILLEGAL, SRA_pIYpN__ILLEGALB, SRA_pIYpN_C_ILLEGAL, SRA_pIYpN_D_ILLEGAL, SRA_pIYpN_E_ILLEGAL, SRA_pIYpN_H_ILLEGAL, SRA_pIYpN_L_ILLEGAL, SRA_pIYpN, SRA_pIYpN_A_ILLEGAL,
	SLL_pIYpN_B_ILLEGAL, SLL_pIYpN_C_ILLEGAL, SLL_pIYpN_D_ILLEGAL, SLL_pIYpN_E_ILLEGAL, SLL_pIYpN_H_ILLEGAL, SLL_pIYpN_L_ILLEGAL, SLL_pIYpN_ILLEGAL, SLL_pIYpN_A_ILLEGAL, SRL_pIYpN__ILLEGALB, SRL_pIYpN_C_ILLEGAL, SRL_pIYpN_D_ILLEGAL, SRL_pIYpN_E_ILLEGAL, SRL_pIYpN_H_ILLEGAL, SRL_pIYpN_L_ILLEGAL, SRL_pIYpN, SRL_pIYpN_A_ILLEGAL,
	BIT_0_pIYpN_ILLEGAL_0, BIT_0_pIYpN_ILLEGAL_1, BIT_0_pIYpN_ILLEGAL_2, BIT_0_pIYpN_ILLEGAL_3, BIT_0_pIYpN_ILLEGAL_4, BIT_0_pIYpN_ILLEGAL_5, BIT_0_pIYpN, BIT_0_pIYpN_ILLEGAL_7, BIT_1_pIYpN_ILLEGAL_0, BIT_1_pIYpN_ILLEGAL_1, BIT_1_pIYpN_ILLEGAL_2, BIT_1_pIYpN_ILLEGAL_3, BIT_1_pIYpN_ILLEGAL_4, BIT_1_pIYpN_ILLEGAL_5, BIT_1_pIYpN, BIT_1_pIYpN_A_ILLEGAL_7,
	BIT_2_pIYpN_ILLEGAL_0, BIT_2_pIYpN_ILLEGAL_1, BIT_2_pIYpN_ILLEGAL_2, BIT_2_pIYpN_ILLEGAL_3, BIT_2_pIYpN_ILLEGAL_4, BIT_2_pIYpN_ILLEGAL_5, BIT_2_pIYpN, BIT_2_pIYpN_ILLEGAL_7, BIT_3_pIYpN_ILLEGAL_0, BIT_3_pIYpN_ILLEGAL_1, BIT_3_pIYpN_ILLEGAL_2, BIT_3_pIYpN_ILLEGAL_3, BIT_3_pIYpN_ILLEGAL_4, BIT_3_pIYpN_ILLEGAL_5, BIT_3_pIYpN, BIT_3_pIYpN_A_ILLEGAL_7,
	BIT_4_pIYpN_ILLEGAL_0, BIT_4_pIYpN_ILLEGAL_1, BIT_4_pIYpN_ILLEGAL_2, BIT_4_pIYpN_ILLEGAL_3, BIT_4_pIYpN_ILLEGAL_4, BIT_4_pIYpN_ILLEGAL_5, BIT_4_pIYpN, BIT_4_pIYpN_ILLEGAL_7, BIT_5_pIYpN_ILLEGAL_0, BIT_5_pIYpN_ILLEGAL_1, BIT_5_pIYpN_ILLEGAL_2, BIT_5_pIYpN_ILLEGAL_3, BIT_5_pIYpN_ILLEGAL_4, BIT_5_pIYpN_ILLEGAL_5, BIT_5_pIYpN, BIT_5_pIYpN_A_ILLEGAL_7,
	BIT_6_pIYpN_ILLEGAL_0, BIT_6_pIYpN_ILLEGAL_1, BIT_6_pIYpN_ILLEGAL_2, BIT_6_pIYpN_ILLEGAL_3, BIT_6_pIYpN_ILLEGAL_4, BIT_6_pIYpN_ILLEGAL_5, BIT_6_pIYpN, BIT_6_pIYpN_ILLEGAL_7, BIT_7_pIYpN_ILLEGAL_0, BIT_7_pIYpN_ILLEGAL_1, BIT_7_pIYpN_ILLEGAL_2, BIT_7_pIYpN_ILLEGAL_3, BIT_7_pIYpN_ILLEGAL_4, BIT_7_pIYpN_ILLEGAL_5, BIT_7_pIYpN, BIT_7_pIYpN_A_ILLEGAL_7,
	RES_0_pIYpN_ILLEGAL_0, RES_0_pIYpN_ILLEGAL_1, RES_0_pIYpN_ILLEGAL_2, RES_0_pIYpN_ILLEGAL_3, RES_0_pIYpN_ILLEGAL_4, RES_0_pIYpN_ILLEGAL_5, RES_0_pIYpN, RES_0_pIYpN_ILLEGAL_7, RES_1_pIYpN_ILLEGAL_0, RES_1_pIYpN_ILLEGAL_1, RES_1_pIYpN_ILLEGAL_2, RES_1_pIYpN_ILLEGAL_3, RES_1_pIYpN_ILLEGAL_4, RES_1_pIYpN_ILLEGAL_5, RES_1_pIYpN, RES_1_pIYpN_A_ILLEGAL_7,
	RES_2_pIYpN_ILLEGAL_0, RES_2_pIYpN_ILLEGAL_1, RES_2_pIYpN_ILLEGAL_2, RES_2_pIYpN_ILLEGAL_3, RES_2_pIYpN_ILLEGAL_4, RES_2_pIYpN_ILLEGAL_5, RES_2_pIYpN, RES_2_pIYpN_ILLEGAL_7, RES_3_pIYpN_ILLEGAL_0, RES_3_pIYpN_ILLEGAL_1, RES_3_pIYpN_ILLEGAL_2, RES_3_pIYpN_ILLEGAL_3, RES_3_pIYpN_ILLEGAL_4, RES_3_pIYpN_ILLEGAL_5, RES_3_pIYpN, RES_3_pIYpN_A_ILLEGAL_7,
	RES_4_pIYpN_ILLEGAL_0, RES_4_pIYpN_ILLEGAL_1, RES_4_pIYpN_ILLEGAL_2, RES_4_pIYpN_ILLEGAL_3, RES_4_pIYpN_ILLEGAL_4, RES_4_pIYpN_ILLEGAL_5, RES_4_pIYpN, RES_4_pIYpN_ILLEGAL_7, RES_5_pIYpN_ILLEGAL_0, RES_5_pIYpN_ILLEGAL_1, RES_5_pIYpN_ILLEGAL_2, RES_5_pIYpN_ILLEGAL_3, RES_5_pIYpN_ILLEGAL_4, RES_5_pIYpN_ILLEGAL_5, RES_5_pIYpN, RES_5_pIYpN_A_ILLEGAL_7,
	RES_6_pIYpN_ILLEGAL_0, RES_6_pIYpN_ILLEGAL_1, RES_6_pIYpN_ILLEGAL_2, RES_6_pIYpN_ILLEGAL_3, RES_6_pIYpN_ILLEGAL_4, RES_6_pIYpN_ILLEGAL_5, RES_6_pIYpN, RES_6_pIYpN_ILLEGAL_7, RES_7_pIYpN_ILLEGAL_0, RES_7_pIYpN_ILLEGAL_1, RES_7_pIYpN_ILLEGAL_2, RES_7_pIYpN_ILLEGAL_3, RES_7_pIYpN_ILLEGAL_4, RES_7_pIYpN_ILLEGAL_5, RES_7_pIYpN, RES_7_pIYpN_A_ILLEGAL_7,
	SET_0_pIYpN_ILLEGAL_0, SET_0_pIYpN_ILLEGAL_1, SET_0_pIYpN_ILLEGAL_2, SET_0_pIYpN_ILLEGAL_3, SET_0_pIYpN_ILLEGAL_4, SET_0_pIYpN_ILLEGAL_5, SET_0_pIYpN, SET_0_pIYpN_ILLEGAL_7, SET_1_pIYpN_ILLEGAL_0, SET_1_pIYpN_ILLEGAL_1, SET_1_pIYpN_ILLEGAL_2, SET_1_pIYpN_ILLEGAL_3, SET_1_pIYpN_ILLEGAL_4, SET_1_pIYpN_ILLEGAL_5, SET_1_pIYpN, SET_1_pIYpN_A_ILLEGAL_7,
	SET_2_pIYpN_ILLEGAL_0, SET_2_pIYpN_ILLEGAL_1, SET_2_pIYpN_ILLEGAL_2, SET_2_pIYpN_ILLEGAL_3, SET_2_pIYpN_ILLEGAL_4, SET_2_pIYpN_ILLEGAL_5, SET_2_pIYpN, SET_2_pIYpN_ILLEGAL_7, SET_3_pIYpN_ILLEGAL_0, SET_3_pIYpN_ILLEGAL_1, SET_3_pIYpN_ILLEGAL_2, SET_3_pIYpN_ILLEGAL_3, SET_3_pIYpN_ILLEGAL_4, SET_3_pIYpN_ILLEGAL_5, SET_3_pIYpN, SET_3_pIYpN_A_ILLEGAL_7,
	SET_4_pIYpN_ILLEGAL_0, SET_4_pIYpN_ILLEGAL_1, SET_4_pIYpN_ILLEGAL_2, SET_4_pIYpN_ILLEGAL_3, SET_4_pIYpN_ILLEGAL_4, SET_4_pIYpN_ILLEGAL_5, SET_4_pIYpN, SET_4_pIYpN_ILLEGAL_7, SET_5_pIYpN_ILLEGAL_0, SET_5_pIYpN_ILLEGAL_1, SET_5_pIYpN_ILLEGAL_2, SET_5_pIYpN_ILLEGAL_3, SET_5_pIYpN_ILLEGAL_4, SET_5_pIYpN_ILLEGAL_5, SET_5_pIYpN, SET_5_pIYpN_A_ILLEGAL_7,
	SET_6_pIYpN_ILLEGAL_0, SET_6_pIYpN_ILLEGAL_1, SET_6_pIYpN_ILLEGAL_2, SET_6_pIYpN_ILLEGAL_3, SET_6_pIYpN_ILLEGAL_4, SET_6_pIYpN_ILLEGAL_5, SET_6_pIYpN, SET_6_pIYpN_ILLEGAL_7, SET_7_pIYpN_ILLEGAL_0, SET_7_pIYpN_ILLEGAL_1, SET_7_pIYpN_ILLEGAL_2, SET_7_pIYpN_ILLEGAL_3, SET_7_pIYpN_ILLEGAL_4, SET_7_pIYpN_ILLEGAL_5, SET_7_pIYpN, SET_7_pIYpN_A_ILLEGAL_7
};
